# https://travis-ci.org/sattila83/Robocar
language: python
python:
  - 2.7
install:
  - pip install pyserial pytest mock pytest-cov coverage codecov
script:
  - py.test --cov=./
after_success:
  - coverage combine
  - codecov